### ISSUE TITLE
Bug - Bild im Darkmode falsch Dargestellt

### ISSUE THREAD

**Issue by Mic-R** [gymh/css-main-website#1]
![image](https://user-images.githubusercontent.com/86645595/125511197-347f3711-85a5-40c1-be5d-e7bf3a43a5e2.png)
Ich denke mal nicht, dass das normal ist 

(Lösungsvorschlag: Weißer Container hintern allen Bildern)

**Comment by Mic-R** [comment]
Mir ist auch aufgefallen, dass dieses verhalten bei schwarzem Test auftritt

**Comment by nicolaiort** [comment]
Bilder werden von der Schule eingestellt => Wer kaputte Bilder einstellt ist selbst schuld.
Weißer Background breaked evtl andere Bilder.

**Comment by Mic-R** [comment]
Das macht Sinn, was ist mit dem Text?

**Comment by philippdormann** [comment]
Für Text gilt das selbe wie für Bilder.
Auf den Inhalt der Website haben wir (ich) keinen Einfluss.

Mir wäre allerdings auch kein konkretes Beispiel bekannt, bei dem es schwarzen Text gibt?? 🧐

**Comment by Mic-R** [comment]
Ich kann mal ein Beispiel senden, dieses könnte jedoch schulsensible Daten enthalten, kann ich euch durch irgendeinen privaten Weg kontaktieren?

**Comment by philippdormann** [comment]
Gern. Kontaktmöglichkeiten findest du auf meiner Website.

**Comment by Mic-R** [comment]
E-Mail gesendet. Über meine Verschlüsselte, persönliche E-Mail

**Comment by philippdormann** [comment]
Danke, behoben.

Schönen Abend,
Philipp.

**Comment by Mic-R** [comment]
Perfekt, geht wieder!
Danke!
